create table CRIME_DAY
(CRIME_TYPE     VARCHAR2(50),
    SUN_CNT     NUMBER(10),
    MON_CNT     NUMBER(10),
    TUE_CNT     NUMBER(10),
    WED_CNT     NUMBER(10),
    THU_CNT     NUMBER(10),
    FRI_CNT     NUMBER(10),
    SAT_CNT     NUMBER(10),
    UNKNOWN_CNT NUMBER(10));
    
