-- 예제_180 SQL로 머신러닝 구현하기2(NAIVEBAYES) 

SET SERVEROUTPUT ON
SET VERIFY OFF

ACCEPT P_CHILLS PROMPT '오한이 있습니까(Y/N) ? '
ACCEPT P_RUNNY_NOSE PROMPT '콧물이 있습니까(Y/N) ? '
ACCEPT P_HEAD_ACHE PROMPT '두통이 있습니까(STRONG/MILD/NO) ? '
ACCEPT P_FEVER PROMPT '열이 있습니까(Y/N) ? ' 

DECLARE  
   V_PRED    VARCHAR2(20);
   V_PROB    NUMBER(10,2);

BEGIN 
WITH TEST_DATA AS (SELECT UPPER('&P_CHILLS') CHILLS ,
UPPER('&P_RUNNY_NOSE') RUNNY_NOSE, 
                           UPPER('&P_HEAD_ACHE') HEADACHE, 
UPPER('&P_FEVER') FEVER
                         FROM DUAL )
SELECT PREDICTION (MD_CLASSIFICATION_MODEL USING *),
       PREDICTION_PROBABILITY(MD_CLASSIFICATION_MODEL USING * )  INTO V_PRED, V_PROB
FROM TEST_DATA;

 IF V_PRED ='Y' THEN 

   DBMS_OUTPUT.PUT_LINE('머신러닝이 예측한 결과: 독감입니다. 
독감일 확률은 ' || ROUND(V_PROB,2) * 100 || '%입니다');

 ELSE 
DBMS_OUTPUT.PUT_LINE('머신러닝이 예측한 결과: 독감이 아닙니다.
독감이 아닐 확률은 ' || ROUND(V_PROB,2) * 100 || '%입니다');

 END IF;

END;
/
